export const JuriFundEscrowAbi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    inputs: [{ internalType: "address", name: "target", type: "address" }],
    name: "AddressEmptyCode",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "AddressInsufficientBalance",
    type: "error",
  },
  { inputs: [], name: "AlreadyInitialized", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "errorCode", type: "uint256" }],
    name: "Exception",
    type: "error",
  },
  { inputs: [], name: "FailedInnerCall", type: "error" },
  { inputs: [], name: "MathOverflowedMulDiv", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "actual", type: "uint256" },
      { internalType: "uint256", name: "expected", type: "uint256" },
    ],
    name: "NotEnoughFunds",
    type: "error",
  },
  { inputs: [], name: "NotInitialized", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "x", type: "uint256" },
      { internalType: "uint256", name: "y", type: "uint256" },
    ],
    name: "PRBMath_MulDiv18_Overflow",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "x", type: "uint256" },
      { internalType: "uint256", name: "y", type: "uint256" },
      { internalType: "uint256", name: "denominator", type: "uint256" },
    ],
    name: "PRBMath_MulDiv_Overflow",
    type: "error",
  },
  {
    inputs: [{ internalType: "UD60x18", name: "x", type: "uint256" }],
    name: "PRBMath_UD60x18_Exp2_InputTooBig",
    type: "error",
  },
  {
    inputs: [{ internalType: "UD60x18", name: "x", type: "uint256" }],
    name: "PRBMath_UD60x18_Log_InputTooSmall",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  { inputs: [], name: "UnAuthorized", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "principal", type: "uint256" },
      { indexed: true, internalType: "address", name: "plaintiff", type: "address" },
      { indexed: false, internalType: "address", name: "lawer", type: "address" },
      { indexed: false, internalType: "address", name: "token", type: "address" },
    ],
    name: "EscrowInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "settlement", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "jurisFundFee", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    name: "EscrowSettled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "amount", type: "uint256" }],
    name: "EtherReceived",
    type: "event",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  { inputs: [], name: "disburse", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [{ internalType: "uint256", name: "precalculatedDebt", type: "uint256" }],
    name: "disburseWithOffChainAPR",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getEscrowData",
    outputs: [
      {
        components: [
          { internalType: "uint128", name: "startTime", type: "uint128" },
          { internalType: "uint112", name: "jurisFundFeePercentage", type: "uint112" },
          { internalType: "uint8", name: "initialized", type: "uint8" },
          { internalType: "uint8", name: "isSettled", type: "uint8" },
          { internalType: "uint256", name: "principal", type: "uint256" },
          { internalType: "contract IERC20", name: "settlementToken", type: "address" },
          { internalType: "address", name: "plaintiff", type: "address" },
          { internalType: "address", name: "plaintiffLawer", type: "address" },
          { internalType: "address", name: "jurisFund", type: "address" },
          { internalType: "address", name: "jurisFundSafe", type: "address" },
        ],
        internalType: "struct EscrowData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "principal", type: "uint256" },
      { internalType: "uint256", name: "apr", type: "uint256" },
      { internalType: "address", name: "plaintiff", type: "address" },
      { internalType: "address", name: "lawer", type: "address" },
      { internalType: "address", name: "multisig", type: "address" },
      { internalType: "contract IERC20", name: "token", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "ready",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract IERC20", name: "token", type: "address" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
